DROP DATABASE IF EXISTS todo;
CREATE DATABASE IF NOT EXISTS todo;
USE todo;
CREATE TABLE tarefas (
	id VARCHAR(100) NOT NULL UNIQUE,
    tarefa VARCHAR(100) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    dtini DATETIME NOT NULL,
    dtfim DATETIME NOT NULL,
    status VARCHAR(100) NOT NULL
);